id: P006734
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:19:59.746165
source_metadata:
  id: bdr:W1PD181166
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས།  ཀར་གླིང་ཞི་ཁྲོའི་སྐོར།
  author: ''
  volumes:
    dc40e88cabad45e8be2276b2a883cc38:
      image_group_id: I1KG16326
      title: ''
      volume_number: 1
      total_pages: 938
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
